# Generated by Django 4.1.2 on 2022-10-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='channel_name',
            new_name='name',
        ),
    ]
