# Generated by Django 4.1.2 on 2022-10-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_channel_name_chatroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
